local t = require("support.runner")
local utils = require("pi-panel.server.utils")

t.describe("base64_encode", function()
  -- RFC 4648 section 10 test vectors
  t.it("encodes empty string", function()
    t.eq(utils.base64_encode(""), "")
  end)
  t.it("encodes 'f' with two pad chars", function()
    t.eq(utils.base64_encode("f"), "Zg==")
  end)
  t.it("encodes 'fo' with one pad char", function()
    t.eq(utils.base64_encode("fo"), "Zm8=")
  end)
  t.it("encodes 'foo' with no padding", function()
    t.eq(utils.base64_encode("foo"), "Zm9v")
  end)
  t.it("encodes 'foob'", function()
    t.eq(utils.base64_encode("foob"), "Zm9vYg==")
  end)
  t.it("encodes 'fooba'", function()
    t.eq(utils.base64_encode("fooba"), "Zm9vYmE=")
  end)
  t.it("encodes 'foobar'", function()
    t.eq(utils.base64_encode("foobar"), "Zm9vYmFy")
  end)
  t.it("encodes bytes with high bit set", function()
    t.eq(utils.base64_encode("\255\255\255"), "////")
    t.eq(utils.base64_encode("\0\0\0"), "AAAA")
  end)
end)
