local t = require("support.runner")
local config = require("pi-panel.config")

t.describe("config.defaults", function()
  t.it("ships the documented terminal and launch defaults", function()
    local d = config.defaults
    t.eq(d.auto_start, true)
    t.eq(d.terminal.provider, "auto")
    t.eq(d.terminal.split_side, "right")
    t.eq(d.terminal.split_width_percentage, 0.30)
    t.eq(d.terminal.auto_close, true)
    t.is_nil(d.pi_cmd)
    t.eq(d.variant, "pi")
  end)
end)

t.describe("config.variant", function()
  t.it("resolves the pi spec by default", function()
    t.eq(config.variant({}).cmd, "pi")
    t.eq(config.variant({ variant = "pi" }).lockfile_dir, "~/.pi/ide")
    t.eq(config.variant({ variant = "pi" }).display, "pi")
  end)

  t.it("resolves the omp spec", function()
    local v = config.variant({ variant = "omp" })
    t.eq(v.cmd, "omp")
    t.eq(v.lockfile_dir, "~/.omp/ide")
    t.eq(v.display, "oh-my-pi")
  end)
end)

t.describe("config.setup", function()
  t.it("deep-merges user options over defaults", function()
    local cfg = config.setup({ terminal = { split_side = "left" } })
    t.eq(cfg.terminal.split_side, "left", "user override applied")
    t.eq(cfg.terminal.provider, "auto", "untouched default preserved")
    t.eq(cfg.terminal.split_width_percentage, 0.30, "sibling default preserved")
  end)

  t.it("does not mutate the defaults table", function()
    config.setup({ terminal = { provider = "native" } })
    t.eq(config.defaults.terminal.provider, "auto")
  end)

  t.it("makes the merged config retrievable via get()", function()
    config.setup({ pi_cmd = "/usr/local/bin/pi" })
    t.eq(config.get().pi_cmd, "/usr/local/bin/pi")
  end)

  t.it("resolves variant fields (cmd/lockfile_dir/display) onto the config", function()
    local cfg = config.setup({ variant = "omp" })
    t.eq(cfg.cmd, "omp")
    t.eq(cfg.lockfile_dir, "~/.omp/ide")
    t.eq(cfg.display, "oh-my-pi")
  end)

  t.it("resolves the pi variant by default", function()
    local cfg = config.setup({})
    t.eq(cfg.cmd, "pi")
    t.eq(cfg.lockfile_dir, "~/.pi/ide")
  end)

  t.it("lets pi_cmd override the variant binary (pi_cmd wins)", function()
    local cfg = config.setup({ variant = "omp", pi_cmd = "/path/to/x" })
    t.eq(cfg.cmd, "/path/to/x", "explicit pi_cmd beats the variant default")
    t.eq(cfg.lockfile_dir, "~/.omp/ide", "lock dir still tracks the variant")
  end)

  t.it("rejects an unknown variant", function()
    t.error_contains(function()
      config.setup({ variant = "pico" })
    end, "variant")
  end)

  t.it("rejects an unknown terminal provider", function()
    t.error_contains(function()
      config.setup({ terminal = { provider = "kitty-banana" } })
    end, "provider")
  end)

  t.it("rejects the not-yet-implemented external provider", function()
    t.error_contains(function()
      config.setup({ terminal = { provider = "external" } })
    end, "provider")
  end)

  t.it("rejects an invalid split_side", function()
    t.error_contains(function()
      config.setup({ terminal = { split_side = "up" } })
    end, "split_side")
  end)

  t.it("rejects an out-of-range split_width_percentage", function()
    t.error_contains(function()
      config.setup({ terminal = { split_width_percentage = 1.5 } })
    end, "split_width_percentage")
  end)
end)

t.describe("config.get", function()
  t.it("returns defaults before setup is called", function()
    -- reset internal state by re-requiring is not possible; emulate by setup({})
    config.setup({})
    t.eq(config.get().terminal.provider, "auto")
  end)
end)
