local t = require("support.runner")
local config = require("pi-panel.config")

t.describe("config.defaults", function()
  t.it("ships the documented terminal and launch defaults", function()
    local d = config.defaults
    t.eq(d.auto_start, true)
    t.eq(d.terminal.provider, "auto")
    t.eq(d.terminal.split_side, "right")
    t.eq(d.terminal.split_width_percentage, 0.30)
    t.eq(d.terminal.auto_close, true)
    t.is_nil(d.pi_cmd)
  end)
end)

t.describe("config.setup", function()
  t.it("deep-merges user options over defaults", function()
    local cfg = config.setup({ terminal = { split_side = "left" } })
    t.eq(cfg.terminal.split_side, "left", "user override applied")
    t.eq(cfg.terminal.provider, "auto", "untouched default preserved")
    t.eq(cfg.terminal.split_width_percentage, 0.30, "sibling default preserved")
  end)

  t.it("does not mutate the defaults table", function()
    config.setup({ terminal = { provider = "native" } })
    t.eq(config.defaults.terminal.provider, "auto")
  end)

  t.it("makes the merged config retrievable via get()", function()
    config.setup({ pi_cmd = "/usr/local/bin/pi" })
    t.eq(config.get().pi_cmd, "/usr/local/bin/pi")
  end)

  t.it("rejects an unknown terminal provider", function()
    t.error_contains(function()
      config.setup({ terminal = { provider = "kitty-banana" } })
    end, "provider")
  end)

  t.it("rejects an invalid split_side", function()
    t.error_contains(function()
      config.setup({ terminal = { split_side = "up" } })
    end, "split_side")
  end)

  t.it("rejects an out-of-range split_width_percentage", function()
    t.error_contains(function()
      config.setup({ terminal = { split_width_percentage = 1.5 } })
    end, "split_width_percentage")
  end)

  t.it("rejects an unknown log_level", function()
    t.error_contains(function()
      config.setup({ log_level = "loud" })
    end, "log_level")
  end)
end)

t.describe("config.get", function()
  t.it("returns defaults before setup is called", function()
    -- reset internal state by re-requiring is not possible; emulate by setup({})
    config.setup({})
    t.eq(config.get().terminal.provider, "auto")
  end)
end)
